# Generated by Django 5.1.7 on 2025-03-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('perecivel', 'Perecível'), ('nao_perecivel', 'Não Perecível')], max_length=20)),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade', models.FloatField()),
                ('data_validade', models.DateField()),
            ],
        ),
    ]
